import type { Metadata } from "next";
import HomeNavbar from "@/components/navbars/HomeNavbar";

export const metadata: Metadata = {
  title: "Team Matrix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full overflow-hidden">
      <HomeNavbar />
      {children}
    </div>
  );
}
